# Generated by Django 3.2.7 on 2021-09-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference_id', models.CharField(max_length=50)),
                ('payment_platform', models.CharField(max_length=50)),
                ('payment_amount', models.IntegerField()),
                ('payment_status', models.BooleanField()),
                ('paymnet_date', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=52, unique=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
