# Generated by Django 3.2.6 on 2021-09-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_description', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_slug', models.SlugField(max_length=255, unique=True)),
                ('product_image', models.ImageField(upload_to='media/')),
                ('stock', models.IntegerField()),
                ('is_new', models.BooleanField(default=False)),
                ('product_size', models.CharField(choices=[('X', 'X'), ('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
    ]
