# Generated by Django 3.2.7 on 2021-09-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
