# Generated by Django 3.2.7 on 2021-10-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=50)),
                ('shipping_date', models.DateField(auto_now_add=True)),
                ('shipping_method', models.CharField(max_length=50)),
                ('shipping_fee', models.CharField(max_length=20)),
                ('order_key', models.CharField(max_length=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordershipping', to='order.order')),
            ],
        ),
    ]
